### ISSUE TITLE
System exceptions on terrain destruction

### ISSUE THREAD

**Issue by cs716** [apetavern/grubs#375]
```2024/06/02 10:26:56.6730[GameMenu] Exception of type 'System.Exception' was thrown.System.Exception: Exception of type 'System.Exception' was thrown.
   at Sandbox.Polygons.PolygonMeshBuilder.FindAboveSweepEdge(Edge& edge) in facepunch.libpolygon/PolygonMeshBuilder.Fill.cs:line 191
   at Sandbox.Polygons.PolygonMeshBuilder.Fill_SplitIntoMonotonicPolygons() in facepunch.libpolygon/PolygonMeshBuilder.Fill.cs:line 275
   at Sandbox.Polygons.PolygonMeshBuilder.Fill() in facepunch.libpolygon/PolygonMeshBuilder.Fill.cs:line 17
   at Sandbox.Sdf.Sdf2DMeshWriter.WriteRenderMesh(Sdf2DLayer layer) in 2D/Sdf2DMeshWriter.cs:line 557
   at Sandbox.Sdf.Sdf2DMeshWriter.Write(Sdf2DArrayData data, Sdf2DLayer layer, Boolean renderMesh, Boolean collisionMesh) in 2D/Sdf2DMeshWriter.cs:line 439
   at Sandbox.Sdf.Sdf2DArray.WriteTo(Sdf2DMeshWriter writer, Sdf2DLayer layer, Boolean renderMesh, Boolean collisionMesh) in 2D/Sdf2DArray.cs:line 161
   at Sandbox.Sdf.Sdf2DChunk.OnUpdateMeshAsync() in 2D/Sdf2DChunk.cs:line 67```

**Comment by trundlr** [comment]
https://github.com/Facepunch/sbox-libpolygon/issues/4
