### ISSUE TITLE
NRE on Equipment

### ISSUE THREAD

**Issue by cs716** [apetavern/grubs#409]
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Grubs.Equipment.Equipment.Holster() in Equipment/Equipment.cs:line 73
   at Sandbox.Rpc.Resume(WrappedMethod m)
   at Sandbox.Component.__rpc_Broadcast(WrappedMethod m, Object[] argumentList)
   at Grubs.Pawn.PlayerInventory.Holster(Int32 slot) in Pawn/PlayerInventory.cs:line 133
   at Grubs.Pawn.Player.EndTurn() in Pawn/Player.cs:line 77
   at Grubs.Gamemodes.Modes.FreeForAllGamemode.<EndTurn>b__28_0() in Gamemodes/Modes/FreeForAllGamemode.cs:line 295
   at Sandbox.Rpc.Resume(WrappedMethod m)
   at Sandbox.Component.__rpc_Broadcast(WrappedMethod m, Object[] argumentList)
   at Grubs.Gamemodes.Modes.FreeForAllGamemode.EndTurn() in Gamemodes/Modes/FreeForAllGamemode.cs:line 294
   at InvokeStub_FreeForAllGamemode.EndTurn(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by DrewBritt** [comment]
https://github.com/apetavern/grubs/commit/ce9330eb00ced0dfd36666fe8cb4998c33471d68

Think this would happen when a player left during their turn.
