### ISSUE TITLE
NRE on RopeBehavior 

### ISSUE THREAD

**Issue by cs716** [apetavern/grubs#417]
System.NullReferenceException: Object reference not set to an instance of an object.
   at Grubs.Helpers.RopeBehavior.DrawRope() in Helpers/RopeBehavior.cs:line 133
   at Grubs.Helpers.RopeBehavior.OnUpdate() in Helpers/RopeBehavior.cs:line 47
   at Sandbox.Component.ExceptionWrap(String name, Action a)

**Comment by cs716** [comment]
Not sure why this would be null .. Here is the referenced line 
![image](https://github.com/apetavern/grubs/assets/29966072/da14226c-d7e7-4ee0-b133-9d27a35af01d)

**Comment by DrewBritt** [comment]
https://github.com/apetavern/grubs/commit/213f71e84a0b3d798c9fdbafe790ad1d9b36959b
